### ISSUE TITLE
Generate MacOS binaries in CI

### ISSUE THREAD

**Issue by ISNIT0** [openzim/libzim#203]
This is important to be able to provide easily `node-libzim` for MacOS.

See: https://github.com/openzim/libzim/issues/199

**Comment by julianharty** [comment]
@ISNIT0 in #199 you mention you've got things working, does that mean we now have binaries that'll work on MacOS? I've downloaded https://download.openzim.org/release/libzim/libzim_linux-x86_64-5.0.0.tar.gz which has 2 libraries in `lib/x86_64-linux-gnu` so I'm not sure whether these would be suitable for `node-libzim` on OSX... Thank you for any help you can provide :)

**Comment by ISNIT0** [comment]
No.
On "install" `@openzim/libzim` (the npm package name of "`node-libzim`") checks the operating system (https://github.com/openzim/node-libzim/blob/master/build/native/binding.gyp#L16), if on MacOS it tries to use an installed version of `libzim`.

`libzim` builds easily and nicely on MacOS now, so shouldn't be too hard based on the readme.
I think it's just:
```
meson . build
ninja -C build install
```
 (when meson and ninja are installed via homebrew)

**Comment by julianharty** [comment]
I have managed to build `libzim` on OSX Sierra (10.12) once I installed a couple of dependencies using homebrew in addition to your suggestions. Here's what I needed to install:

```
brew install icu4c
brew link icu4c --force
export LDFLAGS="-L/usr/local/opt/icu4c/lib"
export CPPFLAGS="-I/usr/local/opt/icu4c/include"
export PKG_CONFIG_PATH="/usr/local/opt/icu4c/lib/pkgconfig"
brew install xapian
```
Notes:
Homebrew refused to apply the `--force` for icu4c and I'm not sure which of the exports did the trick as I had to work out how to convince meson and ninja that the environment had changed (which I ended up doing by removing the locally created build folder (`rm -rf build/`) since the meson commands I'd tried (`meson --reconfigure .` and `meson setup --wipe .`) refused to do my bidding. Clearly I don't understand how these commands are supposed to work...

Anyway in `ls -lart /usr/local/lib` I now have various newly added files including:
```
lrwxr-xr-x    1 julianharty  admin       14 19 Jul 08:10 libzim.dylib -> libzim.5.dylib
-rwxr-xr-x    1 julianharty  admin  1440688 19 Jul 08:10 libzim.5.dylib
```
Onwards and Upwards!

**Comment by kelson42** [comment]
@julianharty What would be really helpful is that you update the travis conf to let him prepare the binaries and upload them to https://download.openzim.org/release/libzim/

**Comment by julianharty** [comment]
@kelson42 I agree. Can you guide me into the practical aspects of doing so? for instance, 
- what OS would we use to compile and build the library? OSX? or cross-compile from linux? 
- where would this machine be? in the cloud? and how would be configure it? 

From reading https://docs.travis-ci.com/user/reference/osx it seems like one of their instances might be a suitable place to build the library for OSX. So the challenge may be working out _how_ to achieve this.

Here are various sources of clues I've found so far...

https://docs.travis-ci.com/user/installing-dependencies/#installing-packages-on-macos
https://ropensci.org/blog/2016/07/12/travis-osx/
https://stackoverflow.com/questions/51566610/travis-deploy-based-on-matrix-parameters
https://github.com/travis-ci/travis-ci/issues/7761

I'll have a think on what I can do next to modify https://github.com/openzim/libzim/blob/master/.travis.yml  accordingly. Suggestions are welcome.

**Comment by julianharty** [comment]
PS: Meanwhile, I've been experimenting on repeating my previous steps of building the library locally on different macbooks (both running 10.12). On my well used machine I've got some old cruft on the machine or in the environment that's causing the compilation to fail. On a recently imaged machine I needed to also install pkg-config which I did using homebrew.

```
git clone https://github.com/openzim/libzim.git
cd libzim/
brew install meson ninja 
brew install icu4c
brew install xapian
brew install pkg-config
meson . build (fails)
```
I then followed the advice from homebrew to configure the runtime environment (in the 4 `EXPORT` statements below) which did the trick after I'd completed the forth of these.
```
ls -lart /usr/local/lib
brew list
brew info icu4c
export PATH="/usr/local/opt/icu4c/bin:$PATH"
export PATH="/usr/local/opt/icu4c/sbin:$PATH"
export LDFLAGS="-L/usr/local/opt/icu4c/lib"
export CPPFLAGS="-I/usr/local/opt/icu4c/include"
export PKG_CONFIG_PATH="/usr/local/opt/icu4c/lib/pkgconfig"
meson . build
ninja -C build install
ls -lart /usr/local/lib
```

**Comment by kelson42** [comment]
@julianharty No, I have never did that, but we already compile for MacOS in the CI and publish the GNU/Linux binaires... so should not be too complicated.

**Comment by julianharty** [comment]
@kelson42 great, please can you point me to the project where we compile for MacOS in the CI. I have looked at kiwix/apple and that doesn't seem to use Travis...

**Comment by kelson42** [comment]
@julianharty Sorry, I thought It does, but in fact in does not https://github.com/openzim/libzim/blob/master/.travis.yml

**Comment by mgautierfr** [comment]
> @kelson42 great, please can you point me to the project where we compile for MacOS in the CI. I have looked at kiwix/apple and that doesn't seem to use Travis...

This is in kiwix-build. (https://github.com/kiwix/kiwix-build/blob/master/.travis.yml#L37-L42)
We already build libzim, zimwriterfs, zim-tools and kiwix-lib. (https://github.com/kiwix/kiwix-build/blob/master/travis/compile_all.py#L404-L406).

However, we originally don't publish library because libzim is compiled dynamically, and so all other dependency are not "included" in the .so and we would have to publish all other .so.
I've especially created the target "native_mixed" to build all dependency statically and libzim dynamically to have a single .so file on linux (https://github.com/kiwix/kiwix-build/pull/289). But I've not tested it on osx.
You may try to build it using `kiwix-build --target-platform native_mixed libzim` to see if it works on macos.
If (once) it works, building libzim in the ci and publish it should be pretty straightforward.

**Comment by julianharty** [comment]
@mgautierfr Thank you for the explanation of the complications. I've created a branch  `julianharty/macOS-homebrew-packages` to experiment with adding any necessary dependencies to build the library on travis for OSX. I've noticed travis already has meson and ninja and I think it also has pkg-config, so I'm guessing that we'll only need to add 2 homebrew packages (xapian and icu4c). I'm waiting to see if travis will automatically build that branch or do I need to create a pull request? As I contribute infrequently please let me know if I'm going astray.

**Comment by julianharty** [comment]
@mgautierfr I've checked the travis docs and it looks like I needed to create a pull request to get travis to build my branch, so I've created a draft pull request here which seems to have been enough to get travis to build the branch.

**Comment by julianharty** [comment]
Travis seemed to find and install the package correctly, and I can see from the travis log that we now satisfy the build requirements AFAIK 

https://travis-ci.org/openzim/libzim/jobs/562007922

Extract follows:
```
Found pkg-config: /usr/local/bin/pkg-config (0.29.2)
Dependency zlib found: YES 1.2.8
Dependency liblzma found: YES 5.2.4
Dependency xapian-core found: YES 1.4.10
Dependency threads found: YES 
Dependency icu-i18n found: YES 58.2
Program libzim-compile-resources found: YES (/Users/travis/build/openzim/libzim/scripts/libzim-compile-resources)
Configuring config.h using configuration
Dependency GTest found: NO (tried pkgconfig and system)
Looking for a fallback subproject for the dependency gtest
|
|Executing subproject gtest 
|
|Project name: gtest
|Project version: 1.8.0
... Tests get run here
```

Ninja claims it has no work to do
```
ninja: Entering directory `/Users/travis/build/openzim/libzim/build'
ninja: no work to do.
```
so I'm guessing we'll need to tweak https://github.com/openzim/libzim/blob/master/travis/compile.sh once we've sorted out the mixed-library build target. I'll change the draft pull request to a full pull request since the xapian homebrew package seems to be all we need at this stage for the compile to work.

**Comment by mgautierfr** [comment]
> Ninja claims it has no work to do

This is ok.
Ninja does it work here :
```
[1/51] Generating resources with a custom command.
stopwords/en ['stopwords', 'en']
stopwords/he ['stopwords', 'he']
stopwords/fra ['stopwords', 'fra']
[51/51] Linking target test/template.
```

Ninja is launch by `meson test` and indeed it has nothing to do because it already does the job.

---
You PR https://github.com/openzim/libzim/pull/247 is useless. We are already building libzim for macos on the CI.
There is no need to install xapian using homebrew because we are already building all the libzim dependencies (including xapian) on kiwix-build side. The dependencies are downloaded and installed by https://github.com/openzim/libzim/blob/master/travis/install_deps.sh#L31-L33

---
Compiling libzim on macos on the CI of libzim is nice because we are sure that every change made on libzim will not break macos. But we need to do the publication on kiwix-build side.

**Comment by kelson42** [comment]
Yes, this ticket should in fact be part of the kiwix-build repo. Unfortunately I don't have the gitmover tool anymore.

**Comment by julianharty** [comment]
Kamino closed and cloned this issue to [kiwix/kiwix-build](https://github.com/kiwix/kiwix-build/issues/349)
