### ISSUE TITLE
Secure M/Counter writing in the libzim

### ISSUE THREAD

**Issue by kelson42** [openzim/libzim#206]
Currently this piece of code is still in `zimwriterfs` so ZIM file created with libzim directly does not have it. They should have something like:
```
$ zimdump -n M -d -f Counter ref.zim 
application/javascript=13;image/gif=2;image/png=30;image/svg+xml=1;text/css=14;text/html=729;
```

**Comment by kelson42** [comment]
@mgautierfr This is a blocker for mwoffliner 1.8, to be fixed ASAP.

**Comment by mgautierfr** [comment]
I'm not sure about this.
Metadata are specific to the "client" of libzim (ie kiwix).

`M/Counter` is not needed for a zim file.
As far as I know, this is only used by kiwix-lib to know the number of media and "displayable article" in a zim file.

As far as possible, I would like to keep the libzim agnostic about the content of a zim file and its usage.

**Comment by kelson42** [comment]
@mgautierfr This is in the spec (but not mandatory) and this is the only way to know what kind of content is in the ZIM file without parsing everything https://wiki.openzim.org/wiki/Metadata#Keys. Kiwix relies on it and I don't want to re implement it in each binding. I see no reason to not have it in the libzim. If this is prefereable, implement it as a switch in the the writer class, a kind of option which needs to be actived.

**Comment by mgautierfr** [comment]
> https://wiki.openzim.org/wiki/Metadata#Keys.

I totally missed this page.

However, I still disagree to include it in libzim. Zim files may be used to store a lot of thing not related to kiwix (simple archive of files, backup, resources embeded in a binary, game assets, ....)
In this case having a Counter (or any other kind of metadata) may not be necessary or even counter productive (Counter could be used for something else).

As you said, kiwix-lib relies on it, but it is the only one to rely on it. I see no reason to add this in our most low level code (and keep in mind that openzim and kiwix are two different projects). ZimCreator do not write any metadata by itself (so, if mwoffliner doesn't add articles in 'M' namespace, there is no metadata at all). If we start to add a counter specific case, we will end to make the API overly complex with special case only used by kiwix (and I spend few times to clean the API to make it generic).

Implementing a counter in higher level language is pretty easy. This is already to the wrapper to detect the mimetype of the articles. It is not complex at all to add a counter (something like half an hour if you know js and mwoffliner). And, because it is specific, it could be implemented by a wrapper far more efficiently that with a counter, a "thing" (web API, bdd information) could give directly this information. (And that a real argument when specific thing should go in specific implementation).

While zimwriterfs was the only client of libzim creator, we could "easily" change thing in both side. But now we will have different clients in different languages implemented by different teams, the smallest is the API, the better it is. I'm almost the only developer working on libzim. And I'm only part time to work on libzim, kiwix-lib, kiwix-build, kiwix-desktop, kiwix-tools and zim-tools. I want to avoid as far as possible thing complex to maintain. And it is already complex enough now.

---

By the way, the Counter thing is currently totally buggy. The only known usage is to count the number of displayable articles ('text/html' mimetype articles) and the number of media. However kiwix-lib count as media only png, jpeg and gif articles. Now we've added video articles in zim files this calculation is mostly wrong.
If I would have to implement this now, I would add a 'M/displayable_articles` and `M/media_articles` with only the number of articles as content. And, as those values are specific to the content stored in the zim (An image may be displayable, and an html may be intended to be included in another article) it would be to the wrapper to fill it, not libzim to compute it at creation or kiwixlib at reading.
But writing it in libzim fixes things that could be wrong and will make thing really more difficult when we will have to fix legacy thing.

And I would have put https://wiki.openzim.org/wiki/Metadata#Keys as a kiwix specification, not zim.

zimwriterfs was doing (and do) the job, and it is good thing it is done there. Mwoffliner has decided to stop to use this intermediate tool (for wrong or good reason that's not the point). It is not to libzim to suddenly support zimwriterfs functionality.

**Comment by kelson42** [comment]
@ISNIT0 Could you please implement this in mwoffliner then?

**Comment by mgautierfr** [comment]
@ISNIT0, Please not this important sentence (in my too long comment) : "if mwoffliner doesn't add articles in 'M' namespace, there is no metadata at all"

So you have to add explicitly metadata articles for author, description, title, ... 
I don't know if you already do it, but it's worth it to mention it :)

**Comment by ISNIT0** [comment]
I'm implementing this in `node-libzim`. On zim finalisation, the counter will be set to the number of articles that have `shouldIndex=true`

**Comment by kelson42** [comment]
@ISNIT0 This counter just contain a list with how many entries the ZIM file has per mime-type. What is the relationship to shouldindex?

**Comment by ISNIT0** [comment]
It seems odd to do it based on `mimeType`, `shouldIndex` seems like a more accurate way to implement this. It's going into the libzim package, so should be done in a generic way

**Comment by kelson42** [comment]
@ISNIT0 You want to rediscuss the spec?

**Comment by ISNIT0** [comment]
> By the way, the Counter thing is currently totally buggy. The only known usage is to count the number of displayable articles ('text/html' mimetype articles) and the number of media. However kiwix-lib count as media only png, jpeg and gif articles.

As far as I can see, there is no spec that is consistently followed. I understand what is at this page https://wiki.openzim.org/wiki/Metadata#Keys But do we want to do only `text/html`? Or actually follow the spec which would break the known usage

**Comment by ISNIT0** [comment]
Okay, I've read things again and understand better what you mean. I'll let you know when I've got a new version

**Comment by ISNIT0** [comment]
node libzim now generates something like this:
`text/plain=7;text/css=18;application/javascript=36;image/png=116;text/html=22;image/svg+xml=21;image/gif=8;image/jpeg=153;video/webm=1`

**Comment by kelson42** [comment]
@ISNIT0 thx
