### ISSUE TITLE
Allow to open a ZIM file from a filedescriptor (in place of file path)

### ISSUE THREAD

**Issue by kelson42** [openzim/libzim#284]
This is necessary to allow embedded custom apps, see https://github.com/kiwix/kiwix-android/issues/56#issuecomment-545403463

**Comment by kelson42** [comment]
@mgautierfr Would it be complicated to allow the libzim to read a ZIM file given a `FILE*`?

**Comment by mgautierfr** [comment]
It would be on a fd (int) instead of a `FILE*`.

Not really complex in itself but it may be a bit tricky to ensure everything is working correctly, with several small changes in the code.

I suppose that the zim file would be at a specific offset "in" the fd ? (not 0).
Will the zim content be at the end of the file or there will be another content after the zim part ? (We check that the file size is consistent with information in the header (checksumPos))

**Comment by kelson42** [comment]
@automactic Would you be able to help us here to identify if things are doable? Like written in https://github.com/kiwix/kiwix-android/issues/1447, it looks like we would have a https://developer.android.com/reference/kotlin/android/content/res/AssetFileDescriptor in java world. Could we get the fd of it in binary world?

**Comment by kelson42** [comment]
Seems somehow needed for this ticket as well https://github.com/kiwix/kiwix-android/issues/2062

**Comment by macgills** [comment]
>Could we get the fd of it in binary world?

https://developer.android.com/reference/android/content/res/AssetFileDescriptor#getFileDescriptor()

yup, seems possible

**Comment by mgautierfr** [comment]
libzim assume the file size is the size of the zim "content". I suppose that reading from the fd, this assuption isn't true anymore.

@macgills Do you confirm ?
Do you have access to the "size" of the zim file you can pass de libzim/kiwix-lib along with the fd ?

**Comment by macgills** [comment]
I am going to guess yes

https://developer.android.com/reference/android/content/res/AssetFileDescriptor#getLength()
