### ISSUE TITLE
Add validity check in libzim.

### ISSUE THREAD

**Issue by mgautierfr** [openzim/libzim#359]
We already have a tool (zimcheck) to check a zim file.

But `zimcheck` somehow is more checking the content of a zim file to ensure it is coherent
(links are good, mandatory metadata, ...).

But the recent bug in libzim (#350) is not about the data but the internal structure of the zim file.
The only way to ensure that a zim file is good is to try to read all content (at least one content in all cluster).
As cluster is an internal concept of libzim, `zimcheck` cannot do it (or have to open all content).

The libzim check should check this bug, but potentially other things :
- Be sure that all offsets are valid (< zim size)
- Clusters are valid.
- No overlap of buffers/arrays
- ...

This check function would be call by `zimcheck` tool.

**Comment by kelson42** [comment]
zimcheck should check everything necessary.

**Comment by mgautierfr** [comment]
Zimcheck has no access to internal structure of a zim file.

**Comment by kelson42** [comment]
OK, we need to think twice about the problem then, I'm reluctant to the idea to have an other ZIM checking tool. Maybe we just need to complete the `zimcheck` with a process trying to access all the content in uncompress clusters.

**Comment by mgautierfr** [comment]
The idea is to have a function in libzim called by zimcheck. No other tool would be created.

**Comment by kelson42** [comment]
> The idea is to have a function in libzim called by zimcheck. No other tool would be created.

Seems good.

**Comment by kelson42** [comment]
@mgautierfr Would you be able to confirm that this ZIM has a structural problem? Zim file: [prepaid-data-sim-card.wikia.com_2019_10.zip](https://github.com/kiwix/kiwix-desktop/files/3692764/prepaid-data-sim-card.wikia.com_2019_10.zip). See https://github.com/kiwix/kiwix-desktop/issues/270

**Comment by mgautierfr** [comment]
It seems that the zim is OK. There is errors in the content of the zim files (wrong link) the binary structure is ok.

**Comment by kelson42** [comment]
Assigning @veloman-yunkan to help polishing the PR.

**Comment by veloman-yunkan** [comment]
@mgautierfr I have the following questions/suggestions:

1. Shouldn't we provide for a way of selecting which checks to run?
2. Some checks from the above list (e.g. the sortedness of `UrlPtrList` and `TitlePtrList`) can be implemented externally using the public API of libzim. Shouldn't they rather be implemented in `zimcheck`?
3. I think that each check that cannot be implemented externally should be a member function of `FileImpl`. The free function `validate()` should just open the ZIM file and call all those checks.
4. How verbose the checks should be? Should the verbosity be controllable by the caller? Should a check bail out as soon as a single violation is found or it should proceed as much as possible (or maybe up to a user specified limit of reported errors)?

**Comment by kelson42** [comment]
Just to be precise, the only expectation I have:
* libzim does not crash if corrupted ZIM file (but this is not in the scope of this ticket)
* libzim proposes a way to validate the ZIM file structure (this ticket).

As a consequence, no real two speed validation, a validation can be done at the runtime only when very cheap to be executed (we don't want to slow down the read/write process). Otherwise in a validation function which will be called on demand. Zimcheck is the only tool so far which will use it.

The structure of the ZIM should be checked in the libzim, everything which regards the content of article (so the sementic of the content) should be checked in zimcheck itself.

For the moment, the only public API change I expect is for the validate() method, I don't expect more granularity. That said would be great to have one method per check in the code (as long as it does not slow down significantly the validation process to keep things in multiple methods).

Regarding the reporting, I'm OK with a boolean returned by the validate() and the details on the STDERR. If you have already a more sophisticated system, I'm glad... but don't want you to invest too much time on build this kind of `Status` class with trhresholds, etc...

Last but not least, I'm glad about feedback from Matthieu which is really helpful. That said I want to avoid too much time invested now on this (we are at the end of the project). So please focus on the already open tickets which are about index sorting and mime-type validation. I'm OK to support other developements if they are short to implement, otherwise I would ask to create new tickets.

**Comment by mgautierfr** [comment]
I've miss the comments on this issue. Sorry. I'm answering here even if my answers are a bit outdated as @kelson42 already answer and you've already made a PR.


> Shouldn't we provide for a way of selecting which checks to run?

As @kelson42 said, it may be nice but not necessary.
You already implement one in #425, it is enough.

> Some checks from the above list (e.g. the sortedness of UrlPtrList and TitlePtrList) can be implemented externally using the public API of libzim. Shouldn't they rather be implemented in zimcheck?

No. The idea is to have all checks related to the zim file structure/format (valid offset, urlPtrlist sorted, ...) being done in the libzim.
Content related checks (valid html links, ...) should be done elsewhere (zimcheck for now)

> I think that each check that cannot be implemented externally should be a member function of FileImpl. 

I had the opposite idea.
I think we should implement checks without using the FileImpl.
Checks may uses other libzim structures (cluster, dirent, ...) by directly reading the interesting part in the zim file (potentially using a `Reader`)
The FileImlp may use fast checks when opening a zim file instead of doing the checks itself.

As you already mention, `FileImpl` is somehow a god object and it becomes to be too big. I think we should slowly split it. It is no time to add more functionalities to it.

> The free function validate() should just open the ZIM file and call all those checks.

But yes, whatever how the checks are implemented, it is better if the validate function just call them.

> How verbose the checks should be? Should the verbosity be controllable by the caller? Should a check bail out as soon as a single violation is found or it should proceed as much as possible (or maybe up to a user specified limit of reported errors)?

Those checks will be run in batch to be sure that zim files created by zimfarm are valid.
The quicker we check them (and stop in case of error) the better it is.
Once we've found a faulty zim file, we (developers) will have time to test the file and run all checks on it.
