### ISSUE TITLE
zimcompDefault is no compression

### ISSUE THREAD

**Issue by rgaudin** [openzim/libzim#371]
Now that we can customize the compression type at creation, I realized that `zimcompDefault` means *no-compression* while it is understood that our *default compression* should be `lzma`, as states the default Creator constructor:

https://github.com/openzim/libzim/blob/63ecb3415d54a68d4cf39d28de05fd7d0bf08cbd/include/zim/writer/creator.h#L35-L37

This behavior is problematic as it would force bindings to manually set the default while the mechanism is already there in the libzim and just not used properly.

**Comment by mgautierfr** [comment]
The problem here is that `zimcompDefault` is not a default value of libzim (api). But a default value of the zim format itself.

We could separate the values used in the zim file from the value we present to the user but we must NOT change the value of `zimcompDefault`.

The best for now is to have the binding using `zimcompLzma` by default if the user doesn't provide a value.

**Comment by rgaudin** [comment]
OK I understand. Will change that in the PR then
