### ISSUE TITLE
Make xapian a mandatory dependency ?

### ISSUE THREAD

**Issue by mgautierfr** [openzim/libzim#409]
For now the xapian dependency is officially optional.

However, building libzim without xapian is not tested and I'm not sure it is actually working.
On top of that, I don't see a real use case of libzim without xapian. Every one is using it.

It would make sense to make xapian mandatory.

@kelson42 What do you think about this ?

**Comment by kelson42** [comment]
@mgautierfr I don't believe it is a good idea.... but I don't have a super strong argument. I propose to keep this ticket open so I think twice and even more about this question. We could gather other opinions as well.

**Comment by mgautierfr** [comment]
In https://github.com/kiwix/kiwix-tools/issues/369 you don't want to add a option to disable fulltext search. If we always want fulltext (and title) search, we should have xapian mandatory.

Do you no some use case of having libzim without xapian ?

**Comment by kelson42** [comment]
If there is a ft index in a ZIM you use it, otherwise not. This ticket about an option for kiwix-serve is totally unrelated to this one.

I had a bit of time to think about this topic and I confirm that I don't want that because there is no question to put this in the spec. And I want the ref implementation to (be able to) stick to the spec.

Xapian dep has been introduced recently in libzim as a shortcut to simplify its integration in Kiwix and tools writting ZIM files. This saves us creating another common library on the top of the libzim. If this approach starts to create problem, then maybe we should reconsider that decision.

Therefore if there any problem or risk compiling or running without Xapian, then I would like to see this reported like usual with a ticket.

**Comment by mgautierfr** [comment]
The main problem I see it is that is it not compiled nor tested (so we don't know if there is bug), and even if it was, no one is using it.
And it make the code more complex, it would be far simpler to make it mandatory.

I have no real other arguments, if/when I will found another ones, I will make you know :)

**Comment by kelson42** [comment]
@mgautierfr It should be documented and tested, because this is optional. This is why, in an attempt to resolve these problems that @JensTimmerman and me keep asking about the documentation about how to compile it without Xapian.

**Comment by JensTimmerman** [comment]
@mgautierfr I was using it and there is a bug, see #320 libzim can currently not be built correctly without having Xapian available on the system.

I do agree it would be far simpler to make it mandatory...
Perhaps for now the bug in the documentation claiming that it is optional could be fixed and then add it aas optionional again if a solution to make it optional has been found?
