### ISSUE TITLE
"/" in path becomes "%2f" when running zimdump

### ISSUE THREAD

**Issue by tarvos21** [openzim/libzim#58]
Hi, when I try to executing `zimdump wikipedia.zim -D wikipedia`, I discover that the "/" character becomes "%2f", for example in the "-" folder, there will be `j%2fjs_module%2fsite.js`, I guess it's `j/js_module/site.js` because I find it in the HTML header.

What may be the problem?

I am running zimdump on macOS to get the static pages of wikipedia. Thanks!

**Comment by mgautierfr** [comment]
Hello @tarvos21.

Zim archive stores filee without hierarchy. Files are store in a key-value dict. There is a small improvement made with the namespace (the first character of the key) but it is only a improvement.

The fact the the key is called url and that key looks like a path is only a historical "mistake" and depends only of how the zim file has been created. The `/` character has no special meaning.
The `/` of the path is transformed to `%2f` because we url encode the key before writing the file.

We may improve this in the future (how we handle `/`) but we have no plan for now.

And we have to be careful about how we write files and how we handle the keys. ie, what to do if the key is `../../../../../etc/passwd` ?

**Comment by tarvos21** [comment]
@mgautierfr I got the idea, thanks!
