### ISSUE TITLE
Matching default Illustration size?

### ISSUE THREAD

**Issue by rgaudin** [openzim/libzim#588]
Current Illustration API is as follows:

``` cpp
class Archive {
    bool hasIllustration(unsigned int size=48) const;
    Item getIllustrationItem(unsigned int size=48) const;
    std::set<unsigned int> getIllustrationSizes() const;
}

class Creator {
    void addIllustration(unsigned int size, const std::string& content);
}
```

Given we have a default retrieval size of `48`, I find it odd that there is no default size on the Creator as well ; especially given we [**require** a 48px Illustration](https://wiki.openzim.org/wiki/Metadata) in the spec: “`Illustration_48x48` is mandatory. Others are optional.”.

Btw, doc should prob. be updated as we currently have `Illustration_48x48@1` and not ``Illustration_48x48`.

So my question is: do we want to hamonize reader and writer here? Either have default=48 everywhere or no default ? Or are we happy we how it is now?

**Comment by veloman-yunkan** [comment]
@rgaudin IMHO, a default value for the `size` parameter is not justified for `zim::Creator`. In fact, there could be no `size` parameter in the `Creator::addIllustration()` method, if it tried to be smart and deduced the illustration dimensions from `content`. But since the current approach in `libzim` is [to keep it simple](https://github.com/openzim/libzim/pull/540#issuecomment-839632387), it is the client's responsibility to specify the size of the illustration item being added. Allowing to omit the size may lead to confusion, possibly resulting in inconsistent data (bad ZIM archives that may escape into the wild and cause us some headache later). Things are different in case of `zim::Archive` - telling it to return an illustration without specifying the size cannot have a negative effect of the same magnitude.

**Comment by rgaudin** [comment]
Makes sense ; although that safety net is very thin as it's as easy to input garbage in this, not respecting neither size nor format and just passing `size=48`. I agree though that not having a default forces one to find-out in the spec or doc what's required 👍

**Comment by mgautierfr** [comment]
You can see default in two ways :
- I can avoid to specify the value if it happens it is 48
- I let you decide what is the best default value, I don't want to decide. It happens it is 48 but the value itself is not really important.

I tend to follow the second way.
In this context, having a default value when reading make sens : "I want a illustration, I don't really care about the size (if I care, I set the size argument)".
But on writing side no, you must tell what is the size of the illustration you are adding.

**Comment by rgaudin** [comment]
OK, thanks for clarifications to both of you.
