### ISSUE TITLE
CI seems to have a dependence to https://mirror.download.kiwix.org/dev/zstd-1.4.5-wrap.zip

### ISSUE THREAD

**Issue by kelson42** [openzim/libzim#663]
This is really strange as it should rely on zstd-1.5.1! It is not clear as well what this version of zstd provides.

**Comment by kelson42** [comment]
After discussion it looks like this could be deleted because now libzstd compiles with Meson

**Comment by mgautierfr** [comment]
Well, now I remember why we use a custom wrap file. It is because there is a check in zstd build system telling that new MSVC compiler is not tested and compilation stop. (See https://github.com/openzim/libzim/actions/runs/3583641940/jobs/6029317289)
I'd removed this check in our custom wrap file.

Not easy to fix (we have to move upstream and probably they have to test compiler and so).

@kelson42, I suggest we move this issue out of this milestone to not block the release.

**Comment by eli-schwartz** [comment]
> Well, now I remember why we use a custom wrap file. It is because there is a check in zstd build system telling that new MSVC compiler is not tested and compilation stop.

Ugh, I know this one.

Way back when this version of zstd was added to the WrapDB, it was reported to not work and upstream zstd even had a PR where they added this exact error message. It just never got merged because I guess they fixed the issue instead. But while it was being discussed, it was included in advance in the WrapDB.

Unfortunately, the WrapDB still ships 1.4.5 -- I have tried to update it a couple times but every time it failed the either the build or the tests for a different reason and I went and submitted upstream fixes. I'm hoping the next version will work... see e.g. https://github.com/mesonbuild/wrapdb/compare/zstd-2

**Comment by kelson42** [comment]
@eli-schwartz Thx, any upstream ticket we should follow to be kept informed?

**Comment by eli-schwartz** [comment]
The zstd `dev` branch can successfully pass wrapdb checks after this PR is manually applied: https://github.com/facebook/zstd/pull/3120

I'm hoping this will be merged before the next release.

**Comment by kelson42** [comment]
https://github.com/facebook/zstd/pull/3120 has been merged. @mgautierfr Does it mean that, once zstd is newly released and used by us, we can remove our custom version?

**Comment by eli-schwartz** [comment]
Yes -- I now have zstd's meson build tested in CI upstream, so this should be in good shape for the next release.

**Comment by kelson42** [comment]
@eli-schwartz Thank you for work and update!
