### ISSUE TITLE
[feature request] get article entry by number

### ISSUE THREAD

**Issue by xiaoyifang** [openzim/libzim#793]
such as `getEntryByNumber(int nthEntry)`

get the nth artcile in the archive.

is `getEntryByClusterOrder` what I want?

**Comment by veloman-yunkan** [comment]
> is `getEntryByClusterOrder` what I want?

That depends on what you want :)

[`zim::Entry zim::Archive::getEntryByPath(entry_index_type idx) const`](https://github.com/openzim/libzim/blob/de514b7b508c02a3522a393a076c146f0da89999/include/zim/archive.h#L219) and/or [`zim::Entry zim::Archive::getEntryByTitle(entry_index_type idx) const`](https://github.com/openzim/libzim/blob/de514b7b508c02a3522a393a076c146f0da89999/include/zim/archive.h#L241) may also meet your requirements if you formulate them more precisely.

**Comment by mgautierfr** [comment]
@xiaoyifang You probably want [getEntryByPath](https://libzim.readthedocs.io/en/latest/api/classzim_1_1Archive.html?highlight=getEntryByClusterOrder#_CPPv4NK3zim7Archive14getEntryByPathE16entry_index_type) as the path order is the "standard" path.
`getEntryByTitle` is the same but using the title order instead of the path.
`getEntryByCluster` is a "unspecified" order (sorted by cluster) which is a more efficient order as it reduce the decompression work.

**Comment by xiaoyifang** [comment]
[getEntryByPath](https://libzim.readthedocs.io/en/latest/api/classzim_1_1Archive.html?highlight=getEntryByClusterOrder#_CPPv4NK3zim7Archive14getEntryByPathE16entry_index_type)

is what I want ,Thanks for the help.
