### ISSUE TITLE
Mess with `zim::Archive::getEntryByPath(const std::string& path)`

### ISSUE THREAD

**Issue by veloman-yunkan** [openzim/libzim#843]
The implementation of `zim::Archive::getEntryByPath(const std::string& path)` is inconsistent with its documentation.

The declaration/documentation states https://github.com/openzim/libzim/blob/56b1d9e7480e4055eda8f28f0046c4bec9bdfbcb/include/zim/archive.h#L221-L230

Note the "The path must contains the namespace" requirement.

However, for ZIM files using the new namespace scheme, the implementation assumes that the path references an item from the `C` namespace. Moreover, it may rewrite the path while looking for the result in the said namespace. https://github.com/openzim/libzim/blob/56b1d9e7480e4055eda8f28f0046c4bec9bdfbcb/src/archive.cpp#L215-L230

It first tries to access the entry with the `C` namespace explicitly added to the path. If no such entry exists, it then replaces the namespace-like component in the path with `C` and tries to return the entry at that path instead. This can lead to false results. Suppose that the ZIM file (utilizing the new namespace scheme) doesn't contain entries under `Q/` or `C/Q/` path prefix. Yet the request for `Q/something` will be converted to `C/something` and that item will be returned if it exists.

Thus for ZIM files utilizing the old namespace scheme `getEntryByPath()` can be used to access any entry, whereas for ZIM files utilizing the new namespace scheme `getEntryByPath()` only returns entries from the `C` namespace and it may cheat while doing so.

**Comment by kelson42** [comment]
@mgautierfr We have to be able to list entries per namespace in the libzim. I strongly oppose the idea that only the namespace C entries are free to the publisher to customize. We should really fix this soon, zimdump been broken, this is a regression and we have real lack of introspection tool.

**Comment by mgautierfr** [comment]
> I strongly oppose the idea that only the namespace C entries are free to the publisher to customize

Well, that was the whole purpose of https://github.com/openzim/libzim/issues/345 and https://github.com/openzim/libzim/pull/406, which is 3 years old.

It was explained in https://github.com/openzim/libzim/issues/325#issue-609126653 (explicitly in `Removing namespace` section)

In https://github.com/openzim/zim-tools/issues/315#issuecomment-1235570245 you explicitly say that "The right approach is probably to remove fully the namespace concept"

If, as you said in https://github.com/openzim/zim-tools/pull/316#pullrequestreview-1749210968 you have fail to know if a zim has a full text index or not, we should probably fix zimdump to give this information with `zimdump info`. (libzim itself already have the [hasFulltextIndex method](https://libzim.readthedocs.io/en/latest/api/classzim_1_1Archive.html#_CPPv4NK3zim7Archive16hasFulltextIndexEv))

**Comment by veloman-yunkan** [comment]
As long as docstrings are concerned, it looks like all API functions mentioning the namespace concept have to be reviewed and their documentation corrected.

**Comment by kelson42** [comment]
@mgautierfr Thank you for your documented feedback. This complete the live discussion we had two weeks ago.

Let me try to better phrase my opinion (and it might have changed since last years):
1 - There is a clear functionality problem at `zimdump` level
2 - There is at least a problem of feature a the libzim problem where we have implicit behaviour, misleading function/method names
3 - I believe pushing the idea that zimdump can not list any namespace except `C` (or maybe `H` at some point) to be an error caused by pushing the concept of namespace abstraction too far (ie. totally unavailable for anything outside the libzim). I might have changed of opinion on this and you have - with talent - argumented against that idea... this stays my feeling.

I might have misunderstanding something around the lizbim7 namespace concept. To me, more probably, this was something always a bit unclear ("fully hide namespaces to everything" vs "hide namespaces to the scraper and readers by providing user friendly primitives") as the main goal was to get things working. The fact that the libzim is not fully "clear" around the namespace depending functions and that zimdump (basically the only tool "presenting" the namespaces) tend the validate this theory.

Today, why we are here does not matter very much. I would be happy to be wrong on the whole line if things are clean and working fine. Getting to that level is the priority. @veloman-yunkan @mgautierfr Could you agree on a plan for both libzim/zimdump so we can move forward?

**Comment by mgautierfr** [comment]
I see two solutions here (which are not exclusives)
- List what is expected for things which "are clean and working fine". (Ie, what features we want in zimdump). Issue openzim/zim-tools#316 is somehow already expecting a way to implement things, it is not a feature request (even if there is nothing wrong with the issue). My point is that we should remove namespace option from zimdump, but we have to list what we want to do with it to check it is ok and see what API we need. THEN, extend the libzim API to provide access to specific data. (We already have API for access user content (`C`), metadata (`M`), xapian databases (through search functions or with `hasFulltextIndex`))
- Add a low level api in libzim to access raw/low structures in zim file. (`FileImpl` may be a good candidate)

**Comment by kelson42** [comment]
> List what is expected for things which "are clean and working fine". (Ie, what features we want in zimdump).

It has been essential to provide namespace independant, high level, functions and helper at both writer and reader level. This has been necessary to make everything robust, simpler and offering a homogenous user experience throug all readers.

But `zimdump` should continue to work like it was, current and past `usage()` are OK. Like said, `zimdump` is not a normal reader, it's an inspection tool. I don't want and I don't know how I want it differently to what the zimdump usage() currently describe. I don't want a special behaviour for this or that namespace in zimdump or if that should exist, this would come on the top of basic namespace related features.

Now, we should:
* Ensure high level functions to be used on a daily base for both readers and writers are really namespace indenpendant and that there is no ambiguity
* Keep low-level functions available for zimdump and actually for anybody wanting to access to libzim internals. We can call them how we want be they need to be clearly available and identifiable.
* Secure the documentation is clear and coherent with the reality.

**Comment by kelson42** [comment]
@veloman-yunkan Are you OK with proposal? @mgautierfr would do the libzim part and you would fix zimdump.

**Comment by kelson42** [comment]
@mgautierfr No feedback from @veloman-yunkan, please carry one with implementation.

**Comment by veloman-yunkan** [comment]
> @veloman-yunkan Are you OK with proposal?

At least I don't have any objections.
